import type { NutritionTotals } from '@/types/meal';

export interface MockFoodItem {
  id: string;
  name: string;
  category: 'protein' | 'carb' | 'vegetable' | 'fruit' | 'dairy' | 'mixed';
  emoji: string;
  servingSize: number;
  servingUnit: string;
  perServing: NutritionTotals;
  mealTypes: string[];
  commonPairings: string[];
  confidenceBase: number;
}

export const foodDatabase: MockFoodItem[] = [
  // ===== PROTEIN (18 items) =====
  {
    id: 'grilled-chicken-breast',
    name: 'Grilled Chicken Breast',
    category: 'protein',
    emoji: '🍗',
    servingSize: 200,
    servingUnit: 'g',
    perServing: { calories: 330, protein_g: 62, carbs_g: 0, fat_g: 7 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['white-rice', 'brown-rice', 'caesar-salad', 'steamed-broccoli', 'mashed-potatoes', 'garden-salad', 'roasted-asparagus', 'sweet-potato', 'sauteed-spinach'],
    confidenceBase: 0.94,
  },
  {
    id: 'salmon-fillet',
    name: 'Salmon Fillet',
    category: 'protein',
    emoji: '🐟',
    servingSize: 180,
    servingUnit: 'g',
    perServing: { calories: 367, protein_g: 40, carbs_g: 0, fat_g: 22 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['white-rice', 'steamed-broccoli', 'roasted-asparagus', 'mashed-potatoes', 'caesar-salad', 'garden-salad'],
    confidenceBase: 0.95,
  },
  {
    id: 'ribeye-steak',
    name: 'Ribeye Steak',
    category: 'protein',
    emoji: '🥩',
    servingSize: 250,
    servingUnit: 'g',
    perServing: { calories: 612, protein_g: 52, carbs_g: 0, fat_g: 44 },
    mealTypes: ['dinner'],
    commonPairings: ['mashed-potatoes', 'french-fries', 'steamed-broccoli', 'roasted-asparagus', 'caesar-salad', 'sauteed-mushrooms', 'baked-potato'],
    confidenceBase: 0.96,
  },
  {
    id: 'pork-chop',
    name: 'Pork Chop',
    category: 'protein',
    emoji: '🐷',
    servingSize: 200,
    servingUnit: 'g',
    perServing: { calories: 410, protein_g: 48, carbs_g: 0, fat_g: 23 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['mashed-potatoes', 'steamed-broccoli', 'green-beans', 'apple', 'coleslaw'],
    confidenceBase: 0.91,
  },
  {
    id: 'turkey-breast',
    name: 'Turkey Breast Slices',
    category: 'protein',
    emoji: '🦃',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 202, protein_g: 44, carbs_g: 0, fat_g: 2 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['mashed-potatoes', 'steamed-carrots', 'green-beans', 'garden-salad', 'whole-wheat-bread'],
    confidenceBase: 0.89,
  },
  {
    id: 'duck-breast',
    name: 'Pan-seared Duck Breast',
    category: 'protein',
    emoji: '🦆',
    servingSize: 180,
    servingUnit: 'g',
    perServing: { calories: 395, protein_g: 34, carbs_g: 0, fat_g: 28 },
    mealTypes: ['dinner'],
    commonPairings: ['roasted-asparagus', 'sweet-potato', 'sauteed-spinach', 'cherry-tomatoes'],
    confidenceBase: 0.87,
  },
  {
    id: 'lamb-chops',
    name: 'Lamb Chops',
    category: 'protein',
    emoji: '🐑',
    servingSize: 200,
    servingUnit: 'g',
    perServing: { calories: 490, protein_g: 44, carbs_g: 0, fat_g: 34 },
    mealTypes: ['dinner'],
    commonPairings: ['mashed-potatoes', 'roasted-asparagus', 'roasted-brussels-sprouts', 'garden-salad', 'sauteed-spinach'],
    confidenceBase: 0.93,
  },
  {
    id: 'beef-patty',
    name: 'Ground Beef Patty',
    category: 'protein',
    emoji: '🍔',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 380, protein_g: 35, carbs_g: 0, fat_g: 26 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['french-fries', 'coleslaw', 'sourdough-bread', 'cheddar-cheese', 'garden-salad'],
    confidenceBase: 0.92,
  },
  {
    id: 'chicken-thigh',
    name: 'Roasted Chicken Thigh',
    category: 'protein',
    emoji: '🍖',
    servingSize: 180,
    servingUnit: 'g',
    perServing: { calories: 398, protein_g: 44, carbs_g: 0, fat_g: 24 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['white-rice', 'steamed-broccoli', 'mashed-potatoes', 'garden-salad', 'french-fries'],
    confidenceBase: 0.92,
  },
  {
    id: 'tilapia-fillet',
    name: 'Tilapia Fillet',
    category: 'protein',
    emoji: '🐠',
    servingSize: 170,
    servingUnit: 'g',
    perServing: { calories: 218, protein_g: 44, carbs_g: 0, fat_g: 4 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['white-rice', 'steamed-broccoli', 'garden-salad', 'sauteed-spinach', 'cherry-tomatoes'],
    confidenceBase: 0.86,
  },
  {
    id: 'shrimp-scampi',
    name: 'Shrimp Scampi',
    category: 'protein',
    emoji: '🍤',
    servingSize: 180,
    servingUnit: 'g',
    perServing: { calories: 280, protein_g: 36, carbs_g: 4, fat_g: 12 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['spaghetti-marinara', 'white-rice', 'garden-salad', 'steamed-broccoli', 'caesar-salad'],
    confidenceBase: 0.90,
  },
  {
    id: 'tuna-steak',
    name: 'Tuna Steak',
    category: 'protein',
    emoji: '🐟',
    servingSize: 180,
    servingUnit: 'g',
    perServing: { calories: 260, protein_g: 48, carbs_g: 0, fat_g: 6 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['white-rice', 'roasted-asparagus', 'caesar-salad', 'steamed-broccoli', 'sauteed-spinach'],
    confidenceBase: 0.91,
  },
  {
    id: 'bacon-strips',
    name: 'Bacon Strips',
    category: 'protein',
    emoji: '🥓',
    servingSize: 60,
    servingUnit: 'g',
    perServing: { calories: 324, protein_g: 22, carbs_g: 1, fat_g: 26 },
    mealTypes: ['breakfast'],
    commonPairings: ['scrambled-eggs', 'butter-toast', 'pancakes', 'waffle', 'bagel'],
    confidenceBase: 0.95,
  },
  {
    id: 'scrambled-eggs',
    name: 'Scrambled Eggs',
    category: 'protein',
    emoji: '🥚',
    servingSize: 200,
    servingUnit: 'g',
    perServing: { calories: 296, protein_g: 24, carbs_g: 2, fat_g: 21 },
    mealTypes: ['breakfast'],
    commonPairings: ['bacon-strips', 'butter-toast', 'sourdough-bread', 'whole-wheat-bread', 'cherry-tomatoes', 'cheddar-cheese'],
    confidenceBase: 0.96,
  },
  {
    id: 'chicken-wings',
    name: 'Chicken Wings',
    category: 'protein',
    emoji: '🍗',
    servingSize: 200,
    servingUnit: 'g',
    perServing: { calories: 430, protein_g: 40, carbs_g: 2, fat_g: 28 },
    mealTypes: ['lunch', 'dinner', 'snack'],
    commonPairings: ['french-fries', 'coleslaw', 'beer'],
    confidenceBase: 0.93,
  },
  {
    id: 'pork-ribs',
    name: 'BBQ Pork Ribs',
    category: 'protein',
    emoji: '🍖',
    servingSize: 300,
    servingUnit: 'g',
    perServing: { calories: 738, protein_g: 60, carbs_g: 36, fat_g: 32 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['french-fries', 'coleslaw', 'baked-potato', 'mashed-potatoes'],
    confidenceBase: 0.90,
  },
  {
    id: 'beef-brisket',
    name: 'Beef Brisket',
    category: 'protein',
    emoji: '🥩',
    servingSize: 200,
    servingUnit: 'g',
    perServing: { calories: 470, protein_g: 50, carbs_g: 0, fat_g: 30 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['mashed-potatoes', 'coleslaw', 'pickled-vegetables', 'white-rice', 'green-beans'],
    confidenceBase: 0.88,
  },
  {
    id: 'cod-fillet',
    name: 'Cod Fillet',
    category: 'protein',
    emoji: '🐟',
    servingSize: 180,
    servingUnit: 'g',
    perServing: { calories: 170, protein_g: 36, carbs_g: 0, fat_g: 2 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['french-fries', 'mashed-potatoes', 'garden-salad', 'steamed-carrots', 'green-beans'],
    confidenceBase: 0.85,
  },

  // ===== CARB (18 items) =====
  {
    id: 'white-rice',
    name: 'White Rice',
    category: 'carb',
    emoji: '🍚',
    servingSize: 200,
    servingUnit: 'g',
    perServing: { calories: 260, protein_g: 5, carbs_g: 56, fat_g: 1 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['grilled-chicken-breast', 'beef-stir-fry', 'salmon-fillet', 'chicken-curry-rice', 'beef-brisket', 'shrimp-scampi', 'chicken-thigh'],
    confidenceBase: 0.97,
  },
  {
    id: 'brown-rice',
    name: 'Brown Rice',
    category: 'carb',
    emoji: '🍚',
    servingSize: 200,
    servingUnit: 'g',
    perServing: { calories: 248, protein_g: 5, carbs_g: 52, fat_g: 2 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['grilled-chicken-breast', 'salmon-fillet', 'chicken-thigh', 'beef-stir-fry', 'steamed-broccoli'],
    confidenceBase: 0.94,
  },
  {
    id: 'fried-rice',
    name: 'Fried Rice',
    category: 'carb',
    emoji: '🍚',
    servingSize: 250,
    servingUnit: 'g',
    perServing: { calories: 440, protein_g: 14, carbs_g: 64, fat_g: 14 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['chicken-wings', 'shrimp-scampi', 'beef-stir-fry', 'dumplings', 'kimchi'],
    confidenceBase: 0.93,
  },
  {
    id: 'spaghetti-marinara',
    name: 'Spaghetti with Marinara',
    category: 'carb',
    emoji: '🍝',
    servingSize: 280,
    servingUnit: 'g',
    perServing: { calories: 440, protein_g: 14, carbs_g: 78, fat_g: 8 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['caesar-salad', 'garden-salad', 'parmesan', 'sourdough-bread', 'sauteed-mushrooms'],
    confidenceBase: 0.95,
  },
  {
    id: 'lo-mein',
    name: 'Lo Mein Noodles',
    category: 'carb',
    emoji: '🍜',
    servingSize: 280,
    servingUnit: 'g',
    perServing: { calories: 480, protein_g: 16, carbs_g: 68, fat_g: 16 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['beef-stir-fry', 'chicken-wings', 'dumplings', 'shrimp-scampi', 'sauteed-spinach'],
    confidenceBase: 0.91,
  },
  {
    id: 'udon-noodles',
    name: 'Udon Noodles',
    category: 'carb',
    emoji: '🍜',
    servingSize: 300,
    servingUnit: 'g',
    perServing: { calories: 380, protein_g: 12, carbs_g: 70, fat_g: 4 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['shrimp-scampi', 'beef-stir-fry', 'kimchi', 'sauteed-mushrooms', 'cherry-tomatoes'],
    confidenceBase: 0.88,
  },
  {
    id: 'sourdough-bread',
    name: 'Sourdough Bread',
    category: 'carb',
    emoji: '🍞',
    servingSize: 80,
    servingUnit: 'g',
    perServing: { calories: 210, protein_g: 8, carbs_g: 40, fat_g: 2 },
    mealTypes: ['breakfast', 'lunch'],
    commonPairings: ['butter', 'scrambled-eggs', 'avocado-half', 'cheddar-cheese'],
    confidenceBase: 0.92,
  },
  {
    id: 'whole-wheat-bread',
    name: 'Whole Wheat Bread',
    category: 'carb',
    emoji: '🍞',
    servingSize: 80,
    servingUnit: 'g',
    perServing: { calories: 200, protein_g: 10, carbs_g: 36, fat_g: 3 },
    mealTypes: ['breakfast', 'lunch'],
    commonPairings: ['turkey-breast', 'scrambled-eggs', 'avocado-half', 'cheddar-cheese'],
    confidenceBase: 0.91,
  },
  {
    id: 'french-fries',
    name: 'French Fries',
    category: 'carb',
    emoji: '🍟',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 430, protein_g: 6, carbs_g: 56, fat_g: 20 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['cheeseburger', 'chicken-sandwich', 'beef-patty', 'cod-fillet', 'chicken-wings'],
    confidenceBase: 0.96,
  },
  {
    id: 'mashed-potatoes',
    name: 'Mashed Potatoes',
    category: 'carb',
    emoji: '🥔',
    servingSize: 200,
    servingUnit: 'g',
    perServing: { calories: 230, protein_g: 4, carbs_g: 36, fat_g: 8 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['ribeye-steak', 'grilled-chicken-breast', 'pork-chop', 'turkey-breast', 'beef-brisket', 'salmon-fillet'],
    confidenceBase: 0.94,
  },
  {
    id: 'baked-potato',
    name: 'Baked Potato',
    category: 'carb',
    emoji: '🥔',
    servingSize: 250,
    servingUnit: 'g',
    perServing: { calories: 330, protein_g: 7, carbs_g: 74, fat_g: 0 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['ribeye-steak', 'sour-cream', 'butter', 'cheddar-cheese', 'grilled-chicken-breast'],
    confidenceBase: 0.92,
  },
  {
    id: 'sweet-potato',
    name: 'Roasted Sweet Potato',
    category: 'carb',
    emoji: '🍠',
    servingSize: 200,
    servingUnit: 'g',
    perServing: { calories: 206, protein_g: 4, carbs_g: 48, fat_g: 0 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['grilled-chicken-breast', 'salmon-fillet', 'duck-breast', 'steamed-broccoli', 'green-beans'],
    confidenceBase: 0.90,
  },
  {
    id: 'butter-toast',
    name: 'Buttered Toast',
    category: 'carb',
    emoji: '🍞',
    servingSize: 60,
    servingUnit: 'g',
    perServing: { calories: 190, protein_g: 5, carbs_g: 28, fat_g: 7 },
    mealTypes: ['breakfast'],
    commonPairings: ['scrambled-eggs', 'bacon-strips', 'avocado-half'],
    confidenceBase: 0.96,
  },
  {
    id: 'bagel',
    name: 'Plain Bagel',
    category: 'carb',
    emoji: '🥯',
    servingSize: 120,
    servingUnit: 'g',
    perServing: { calories: 320, protein_g: 12, carbs_g: 62, fat_g: 3 },
    mealTypes: ['breakfast', 'lunch'],
    commonPairings: ['cream-cheese', 'scrambled-eggs', 'avocado-half', 'bacon-strips'],
    confidenceBase: 0.94,
  },
  {
    id: 'croissant',
    name: 'Butter Croissant',
    category: 'carb',
    emoji: '🥐',
    servingSize: 80,
    servingUnit: 'g',
    perServing: { calories: 310, protein_g: 6, carbs_g: 34, fat_g: 18 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['scrambled-eggs', 'butter'],
    confidenceBase: 0.95,
  },
  {
    id: 'pancakes',
    name: 'Pancakes',
    category: 'carb',
    emoji: '🥞',
    servingSize: 180,
    servingUnit: 'g',
    perServing: { calories: 390, protein_g: 10, carbs_g: 62, fat_g: 12 },
    mealTypes: ['breakfast'],
    commonPairings: ['butter', 'bacon-strips', 'scrambled-eggs', 'mixed-berries'],
    confidenceBase: 0.97,
  },
  {
    id: 'waffle',
    name: 'Belgian Waffle',
    category: 'carb',
    emoji: '🧇',
    servingSize: 130,
    servingUnit: 'g',
    perServing: { calories: 380, protein_g: 8, carbs_g: 54, fat_g: 15 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['whipped-cream', 'strawberries', 'bacon-strips', 'blueberries'],
    confidenceBase: 0.94,
  },
  {
    id: 'ramen-noodles',
    name: 'Ramen Noodles',
    category: 'carb',
    emoji: '🍜',
    servingSize: 400,
    servingUnit: 'g',
    perServing: { calories: 560, protein_g: 20, carbs_g: 64, fat_g: 24 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['scrambled-eggs', 'kimchi', 'sauteed-spinach'],
    confidenceBase: 0.91,
  },

  // ===== VEGETABLE (17 items) =====
  {
    id: 'caesar-salad',
    name: 'Caesar Salad',
    category: 'vegetable',
    emoji: '🥗',
    servingSize: 200,
    servingUnit: 'g',
    perServing: { calories: 270, protein_g: 10, carbs_g: 14, fat_g: 20 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['grilled-chicken-breast', 'salmon-fillet', 'spaghetti-marinara', 'shrimp-scampi', 'chicken-caesar-wrap', 'tuna-steak'],
    confidenceBase: 0.95,
  },
  {
    id: 'garden-salad',
    name: 'Garden Salad',
    category: 'vegetable',
    emoji: '🥗',
    servingSize: 180,
    servingUnit: 'g',
    perServing: { calories: 70, protein_g: 3, carbs_g: 12, fat_g: 2 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['grilled-chicken-breast', 'salmon-fillet', 'ribeye-steak', 'spaghetti-marinara', 'cod-fillet', 'pork-chop'],
    confidenceBase: 0.93,
  },
  {
    id: 'steamed-broccoli',
    name: 'Steamed Broccoli',
    category: 'vegetable',
    emoji: '🥦',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 52, protein_g: 4, carbs_g: 10, fat_g: 0 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['grilled-chicken-breast', 'salmon-fillet', 'ribeye-steak', 'white-rice', 'brown-rice', 'beef-stir-fry'],
    confidenceBase: 0.94,
  },
  {
    id: 'roasted-asparagus',
    name: 'Roasted Asparagus',
    category: 'vegetable',
    emoji: '🌿',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 54, protein_g: 4, carbs_g: 6, fat_g: 2 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['salmon-fillet', 'ribeye-steak', 'grilled-chicken-breast', 'duck-breast', 'lamb-chops'],
    confidenceBase: 0.89,
  },
  {
    id: 'sauteed-spinach',
    name: 'Sauteed Spinach',
    category: 'vegetable',
    emoji: '🥬',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 58, protein_g: 4, carbs_g: 6, fat_g: 3 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['salmon-fillet', 'grilled-chicken-breast', 'duck-breast', 'tuna-steak', 'scrambled-eggs'],
    confidenceBase: 0.88,
  },
  {
    id: 'grilled-zucchini',
    name: 'Grilled Zucchini',
    category: 'vegetable',
    emoji: '🥒',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 42, protein_g: 2, carbs_g: 6, fat_g: 2 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['grilled-chicken-breast', 'salmon-fillet', 'lamb-chops', 'beef-patty'],
    confidenceBase: 0.86,
  },
  {
    id: 'cherry-tomatoes',
    name: 'Cherry Tomatoes',
    category: 'vegetable',
    emoji: '🍅',
    servingSize: 120,
    servingUnit: 'g',
    perServing: { calories: 30, protein_g: 1, carbs_g: 6, fat_g: 0 },
    mealTypes: ['lunch', 'dinner', 'snack'],
    commonPairings: ['garden-salad', 'mozzarella', 'caesar-salad', 'sauteed-spinach'],
    confidenceBase: 0.93,
  },
  {
    id: 'cucumber-slices',
    name: 'Cucumber Slices',
    category: 'vegetable',
    emoji: '🥒',
    servingSize: 120,
    servingUnit: 'g',
    perServing: { calories: 18, protein_g: 1, carbs_g: 3, fat_g: 0 },
    mealTypes: ['lunch', 'dinner', 'snack'],
    commonPairings: ['garden-salad', 'cherry-tomatoes', 'feta-cheese', 'greek-yogurt'],
    confidenceBase: 0.94,
  },
  {
    id: 'roasted-brussels-sprouts',
    name: 'Roasted Brussels Sprouts',
    category: 'vegetable',
    emoji: '🥬',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 80, protein_g: 6, carbs_g: 14, fat_g: 1 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['grilled-chicken-breast', 'ribeye-steak', 'lamb-chops', 'salmon-fillet'],
    confidenceBase: 0.87,
  },
  {
    id: 'green-beans',
    name: 'Steamed Green Beans',
    category: 'vegetable',
    emoji: '🫘',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 46, protein_g: 3, carbs_g: 10, fat_g: 0 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['grilled-chicken-breast', 'turkey-breast', 'pork-chop', 'cod-fillet', 'beef-stir-fry'],
    confidenceBase: 0.90,
  },
  {
    id: 'coleslaw',
    name: 'Coleslaw',
    category: 'vegetable',
    emoji: '🥗',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 130, protein_g: 2, carbs_g: 18, fat_g: 6 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['cheeseburger', 'pork-ribs', 'chicken-wings', 'beef-brisket'],
    confidenceBase: 0.91,
  },
  {
    id: 'kimchi',
    name: 'Kimchi',
    category: 'vegetable',
    emoji: '🥬',
    servingSize: 80,
    servingUnit: 'g',
    perServing: { calories: 18, protein_g: 1, carbs_g: 4, fat_g: 0 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['white-rice', 'fried-rice', 'ramen-noodles', 'bibimbap', 'beef-stir-fry'],
    confidenceBase: 0.89,
  },
  {
    id: 'sauteed-mushrooms',
    name: 'Sauteed Mushrooms',
    category: 'vegetable',
    emoji: '🍄',
    servingSize: 120,
    servingUnit: 'g',
    perServing: { calories: 55, protein_g: 4, carbs_g: 4, fat_g: 3 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['ribeye-steak', 'grilled-chicken-breast', 'spaghetti-marinara', 'beef-patty'],
    confidenceBase: 0.87,
  },
  {
    id: 'bell-peppers',
    name: 'Roasted Bell Peppers',
    category: 'vegetable',
    emoji: '🫑',
    servingSize: 120,
    servingUnit: 'g',
    perServing: { calories: 40, protein_g: 1, carbs_g: 8, fat_g: 0 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['beef-stir-fry', 'grilled-chicken-breast', 'chicken-tacos', 'garden-salad', 'lo-mein'],
    confidenceBase: 0.89,
  },
  {
    id: 'steamed-carrots',
    name: 'Steamed Carrots',
    category: 'vegetable',
    emoji: '🥕',
    servingSize: 130,
    servingUnit: 'g',
    perServing: { calories: 45, protein_g: 1, carbs_g: 10, fat_g: 0 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['grilled-chicken-breast', 'turkey-breast', 'cod-fillet', 'mashed-potatoes', 'pork-chop'],
    confidenceBase: 0.92,
  },
  {
    id: 'kale-salad',
    name: 'Kale Salad',
    category: 'vegetable',
    emoji: '🥬',
    servingSize: 180,
    servingUnit: 'g',
    perServing: { calories: 130, protein_g: 5, carbs_g: 18, fat_g: 5 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['grilled-chicken-breast', 'salmon-fillet', 'avocado-half', 'feta-cheese'],
    confidenceBase: 0.88,
  },
  {
    id: 'pickled-vegetables',
    name: 'Pickled Vegetables',
    category: 'vegetable',
    emoji: '🥒',
    servingSize: 80,
    servingUnit: 'g',
    perServing: { calories: 15, protein_g: 0, carbs_g: 3, fat_g: 0 },
    mealTypes: ['lunch', 'dinner', 'snack'],
    commonPairings: ['beef-brisket', 'bibimbap', 'pork-ribs', 'cheeseburger'],
    confidenceBase: 0.90,
  },

  // ===== FRUIT (17 items) =====
  {
    id: 'apple',
    name: 'Apple',
    category: 'fruit',
    emoji: '🍎',
    servingSize: 180,
    servingUnit: 'g',
    perServing: { calories: 95, protein_g: 1, carbs_g: 28, fat_g: 0 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['cheddar-cheese', 'greek-yogurt'],
    confidenceBase: 0.98,
  },
  {
    id: 'banana',
    name: 'Banana',
    category: 'fruit',
    emoji: '🍌',
    servingSize: 120,
    servingUnit: 'g',
    perServing: { calories: 105, protein_g: 1, carbs_g: 27, fat_g: 0 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['greek-yogurt', 'strawberries', 'whole-milk', 'pancakes'],
    confidenceBase: 0.98,
  },
  {
    id: 'orange',
    name: 'Orange',
    category: 'fruit',
    emoji: '🍊',
    servingSize: 180,
    servingUnit: 'g',
    perServing: { calories: 85, protein_g: 2, carbs_g: 21, fat_g: 0 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['greek-yogurt', 'mixed-berries', 'banana'],
    confidenceBase: 0.97,
  },
  {
    id: 'mixed-berries',
    name: 'Mixed Berries',
    category: 'fruit',
    emoji: '🫐',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 86, protein_g: 1, carbs_g: 22, fat_g: 0 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['greek-yogurt', 'pancakes', 'waffle', 'vanilla-ice-cream', 'yogurt-parfait'],
    confidenceBase: 0.95,
  },
  {
    id: 'grapes',
    name: 'Grapes',
    category: 'fruit',
    emoji: '🍇',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 104, protein_g: 1, carbs_g: 27, fat_g: 0 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['cheddar-cheese', 'apple', 'greek-yogurt'],
    confidenceBase: 0.96,
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    category: 'fruit',
    emoji: '🍉',
    servingSize: 250,
    servingUnit: 'g',
    perServing: { calories: 75, protein_g: 2, carbs_g: 18, fat_g: 0 },
    mealTypes: ['breakfast', 'snack', 'lunch'],
    commonPairings: ['feta-cheese', 'cucumber-slices'],
    confidenceBase: 0.93,
  },
  {
    id: 'mango-slices',
    name: 'Mango Slices',
    category: 'fruit',
    emoji: '🥭',
    servingSize: 165,
    servingUnit: 'g',
    perServing: { calories: 107, protein_g: 1, carbs_g: 28, fat_g: 0 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['greek-yogurt', 'strawberries', 'pineapple-chunks', 'yogurt-parfait'],
    confidenceBase: 0.92,
  },
  {
    id: 'pineapple-chunks',
    name: 'Pineapple Chunks',
    category: 'fruit',
    emoji: '🍍',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 75, protein_g: 1, carbs_g: 20, fat_g: 0 },
    mealTypes: ['breakfast', 'snack', 'lunch'],
    commonPairings: ['mango-slices', 'greek-yogurt', 'strawberries', 'mixed-berries'],
    confidenceBase: 0.93,
  },
  {
    id: 'peach',
    name: 'Peach',
    category: 'fruit',
    emoji: '🍑',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 59, protein_g: 1, carbs_g: 15, fat_g: 0 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['greek-yogurt', 'blueberries', 'vanilla-ice-cream'],
    confidenceBase: 0.92,
  },
  {
    id: 'avocado-half',
    name: 'Avocado Half',
    category: 'fruit',
    emoji: '🥑',
    servingSize: 100,
    servingUnit: 'g',
    perServing: { calories: 160, protein_g: 2, carbs_g: 10, fat_g: 15 },
    mealTypes: ['breakfast', 'lunch'],
    commonPairings: ['sourdough-bread', 'scrambled-eggs', 'cherry-tomatoes', 'kale-salad', 'chicken-sandwich'],
    confidenceBase: 0.94,
  },
  {
    id: 'strawberries',
    name: 'Strawberries',
    category: 'fruit',
    emoji: '🍓',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 48, protein_g: 1, carbs_g: 12, fat_g: 0 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['greek-yogurt', 'vanilla-ice-cream', 'waffle', 'whipped-cream'],
    confidenceBase: 0.96,
  },
  {
    id: 'blueberries',
    name: 'Blueberries',
    category: 'fruit',
    emoji: '🫐',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 85, protein_g: 1, carbs_g: 21, fat_g: 0 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['greek-yogurt', 'pancakes', 'waffle', 'yogurt-parfait'],
    confidenceBase: 0.95,
  },
  {
    id: 'pear',
    name: 'Pear',
    category: 'fruit',
    emoji: '🍐',
    servingSize: 180,
    servingUnit: 'g',
    perServing: { calories: 100, protein_g: 1, carbs_g: 27, fat_g: 0 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['greek-yogurt'],
    confidenceBase: 0.91,
  },
  {
    id: 'kiwi',
    name: 'Kiwi',
    category: 'fruit',
    emoji: '🥝',
    servingSize: 140,
    servingUnit: 'g',
    perServing: { calories: 85, protein_g: 2, carbs_g: 21, fat_g: 1 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['strawberries', 'greek-yogurt', 'banana', 'mixed-berries'],
    confidenceBase: 0.92,
  },
  {
    id: 'cherries',
    name: 'Cherries',
    category: 'fruit',
    emoji: '🍒',
    servingSize: 140,
    servingUnit: 'g',
    perServing: { calories: 87, protein_g: 1, carbs_g: 22, fat_g: 0 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['greek-yogurt', 'vanilla-ice-cream', 'mixed-berries'],
    confidenceBase: 0.91,
  },
  {
    id: 'papaya',
    name: 'Papaya',
    category: 'fruit',
    emoji: '🏝️',
    servingSize: 160,
    servingUnit: 'g',
    perServing: { calories: 69, protein_g: 1, carbs_g: 17, fat_g: 0 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['greek-yogurt', 'mango-slices', 'pineapple-chunks'],
    confidenceBase: 0.85,
  },
  {
    id: 'dried-apricots',
    name: 'Dried Apricots',
    category: 'fruit',
    emoji: '🍑',
    servingSize: 50,
    servingUnit: 'g',
    perServing: { calories: 157, protein_g: 2, carbs_g: 35, fat_g: 0 },
    mealTypes: ['snack'],
    commonPairings: ['greek-yogurt', 'cheddar-cheese'],
    confidenceBase: 0.87,
  },

  // ===== DAIRY (15 items) =====
  {
    id: 'greek-yogurt',
    name: 'Greek Yogurt with Honey',
    category: 'dairy',
    emoji: '🍯',
    servingSize: 200,
    servingUnit: 'g',
    perServing: { calories: 160, protein_g: 20, carbs_g: 18, fat_g: 0 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['mixed-berries', 'banana', 'blueberries', 'strawberries', 'apple', 'mango-slices'],
    confidenceBase: 0.95,
  },
  {
    id: 'whole-milk',
    name: 'Whole Milk',
    category: 'dairy',
    emoji: '🥛',
    servingSize: 250,
    servingUnit: 'ml',
    perServing: { calories: 150, protein_g: 8, carbs_g: 12, fat_g: 8 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['pancakes', 'waffle', 'chocolate-chip-cookie'],
    confidenceBase: 0.97,
  },
  {
    id: 'cheddar-cheese',
    name: 'Cheddar Cheese',
    category: 'dairy',
    emoji: '🧀',
    servingSize: 30,
    servingUnit: 'g',
    perServing: { calories: 120, protein_g: 7, carbs_g: 0, fat_g: 10 },
    mealTypes: ['lunch', 'dinner', 'snack'],
    commonPairings: ['cheeseburger', 'apple', 'sourdough-bread', 'scrambled-eggs', 'grapes'],
    confidenceBase: 0.94,
  },
  {
    id: 'cottage-cheese',
    name: 'Cottage Cheese',
    category: 'dairy',
    emoji: '🧀',
    servingSize: 150,
    servingUnit: 'g',
    perServing: { calories: 130, protein_g: 18, carbs_g: 6, fat_g: 3 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['peach', 'pineapple-chunks', 'cherry-tomatoes', 'strawberries', 'whole-wheat-bread'],
    confidenceBase: 0.88,
  },
  {
    id: 'mozzarella',
    name: 'Mozzarella Cheese',
    category: 'dairy',
    emoji: '🧀',
    servingSize: 60,
    servingUnit: 'g',
    perServing: { calories: 168, protein_g: 13, carbs_g: 2, fat_g: 12 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['cherry-tomatoes', 'basil', 'spaghetti-marinara', 'lasagna', 'pepperoni-pizza'],
    confidenceBase: 0.91,
  },
  {
    id: 'cream-cheese',
    name: 'Cream Cheese',
    category: 'dairy',
    emoji: '🧈',
    servingSize: 30,
    servingUnit: 'g',
    perServing: { calories: 100, protein_g: 2, carbs_g: 1, fat_g: 10 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['bagel', 'sourdough-bread', 'cucumber-slices'],
    confidenceBase: 0.93,
  },
  {
    id: 'butter',
    name: 'Butter',
    category: 'dairy',
    emoji: '🧈',
    servingSize: 15,
    servingUnit: 'g',
    perServing: { calories: 102, protein_g: 0, carbs_g: 0, fat_g: 12 },
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    commonPairings: ['sourdough-bread', 'pancakes', 'butter-toast', 'mashed-potatoes', 'baked-potato', 'croissant'],
    confidenceBase: 0.95,
  },
  {
    id: 'sour-cream',
    name: 'Sour Cream',
    category: 'dairy',
    emoji: '🥛',
    servingSize: 30,
    servingUnit: 'g',
    perServing: { calories: 60, protein_g: 1, carbs_g: 1, fat_g: 6 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['baked-potato', 'chicken-tacos', 'beef-burrito', 'mashed-potatoes'],
    confidenceBase: 0.92,
  },
  {
    id: 'vanilla-ice-cream',
    name: 'Vanilla Ice Cream',
    category: 'dairy',
    emoji: '🍦',
    servingSize: 130,
    servingUnit: 'g',
    perServing: { calories: 273, protein_g: 5, carbs_g: 34, fat_g: 14 },
    mealTypes: ['snack'],
    commonPairings: ['chocolate-chip-cookie', 'strawberries', 'cherries', 'mixed-berries'],
    confidenceBase: 0.96,
  },
  {
    id: 'chocolate-milkshake',
    name: 'Chocolate Milkshake',
    category: 'dairy',
    emoji: '🥤',
    servingSize: 350,
    servingUnit: 'ml',
    perServing: { calories: 480, protein_g: 12, carbs_g: 72, fat_g: 16 },
    mealTypes: ['snack'],
    commonPairings: ['cheeseburger', 'french-fries', 'chocolate-chip-cookie'],
    confidenceBase: 0.93,
  },
  {
    id: 'feta-cheese',
    name: 'Feta Cheese',
    category: 'dairy',
    emoji: '🧀',
    servingSize: 40,
    servingUnit: 'g',
    perServing: { calories: 100, protein_g: 6, carbs_g: 2, fat_g: 8 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['garden-salad', 'watermelon', 'cucumber-slices', 'cherry-tomatoes', 'kale-salad'],
    confidenceBase: 0.89,
  },
  {
    id: 'parmesan',
    name: 'Parmesan Cheese',
    category: 'dairy',
    emoji: '🧀',
    servingSize: 20,
    servingUnit: 'g',
    perServing: { calories: 80, protein_g: 8, carbs_g: 0, fat_g: 5 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['spaghetti-marinara', 'caesar-salad', 'lasagna'],
    confidenceBase: 0.92,
  },
  {
    id: 'whipped-cream',
    name: 'Whipped Cream',
    category: 'dairy',
    emoji: '🍦',
    servingSize: 30,
    servingUnit: 'g',
    perServing: { calories: 75, protein_g: 0, carbs_g: 1, fat_g: 8 },
    mealTypes: ['snack'],
    commonPairings: ['waffle', 'pancakes', 'strawberries', 'vanilla-ice-cream'],
    confidenceBase: 0.94,
  },
  {
    id: 'yogurt-parfait',
    name: 'Yogurt Parfait',
    category: 'dairy',
    emoji: '🍨',
    servingSize: 250,
    servingUnit: 'g',
    perServing: { calories: 310, protein_g: 14, carbs_g: 48, fat_g: 8 },
    mealTypes: ['breakfast', 'snack'],
    commonPairings: ['mixed-berries', 'blueberries', 'strawberries', 'mango-slices'],
    confidenceBase: 0.91,
  },
  {
    id: 'string-cheese',
    name: 'String Cheese',
    category: 'dairy',
    emoji: '🧀',
    servingSize: 28,
    servingUnit: 'g',
    perServing: { calories: 80, protein_g: 7, carbs_g: 1, fat_g: 6 },
    mealTypes: ['snack'],
    commonPairings: ['apple', 'grapes'],
    confidenceBase: 0.93,
  },

  // ===== MIXED (15 items) =====
  {
    id: 'pepperoni-pizza',
    name: 'Pepperoni Pizza',
    category: 'mixed',
    emoji: '🍕',
    servingSize: 220,
    servingUnit: 'g',
    perServing: { calories: 596, protein_g: 26, carbs_g: 62, fat_g: 26 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['caesar-salad', 'garden-salad', 'chicken-wings'],
    confidenceBase: 0.97,
  },
  {
    id: 'cheeseburger',
    name: 'Cheeseburger',
    category: 'mixed',
    emoji: '🍔',
    servingSize: 250,
    servingUnit: 'g',
    perServing: { calories: 620, protein_g: 36, carbs_g: 42, fat_g: 34 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['french-fries', 'coleslaw', 'pickled-vegetables', 'chocolate-milkshake'],
    confidenceBase: 0.98,
  },
  {
    id: 'chicken-sandwich',
    name: 'Chicken Sandwich',
    category: 'mixed',
    emoji: '🥪',
    servingSize: 240,
    servingUnit: 'g',
    perServing: { calories: 480, protein_g: 34, carbs_g: 44, fat_g: 18 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['french-fries', 'garden-salad', 'coleslaw'],
    confidenceBase: 0.93,
  },
  {
    id: 'beef-burrito',
    name: 'Beef Burrito',
    category: 'mixed',
    emoji: '🌯',
    servingSize: 350,
    servingUnit: 'g',
    perServing: { calories: 680, protein_g: 38, carbs_g: 70, fat_g: 26 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['white-rice', 'sour-cream', 'bell-peppers', 'cherry-tomatoes'],
    confidenceBase: 0.91,
  },
  {
    id: 'chicken-tacos',
    name: 'Chicken Tacos',
    category: 'mixed',
    emoji: '🌮',
    servingSize: 250,
    servingUnit: 'g',
    perServing: { calories: 450, protein_g: 34, carbs_g: 38, fat_g: 16 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['sour-cream', 'bell-peppers', 'cherry-tomatoes'],
    confidenceBase: 0.90,
  },
  {
    id: 'pad-thai',
    name: 'Pad Thai',
    category: 'mixed',
    emoji: '🍜',
    servingSize: 350,
    servingUnit: 'g',
    perServing: { calories: 580, protein_g: 24, carbs_g: 72, fat_g: 20 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['shrimp-scampi', 'kimchi'],
    confidenceBase: 0.90,
  },
  {
    id: 'sushi-roll',
    name: 'Sushi Roll',
    category: 'mixed',
    emoji: '🍣',
    servingSize: 250,
    servingUnit: 'g',
    perServing: { calories: 370, protein_g: 20, carbs_g: 60, fat_g: 4 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['garden-salad'],
    confidenceBase: 0.94,
  },
  {
    id: 'mac-and-cheese',
    name: 'Mac and Cheese',
    category: 'mixed',
    emoji: '🧀',
    servingSize: 280,
    servingUnit: 'g',
    perServing: { calories: 530, protein_g: 22, carbs_g: 60, fat_g: 24 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['steamed-broccoli', 'garden-salad'],
    confidenceBase: 0.96,
  },
  {
    id: 'lasagna',
    name: 'Lasagna',
    category: 'mixed',
    emoji: '🍝',
    servingSize: 350,
    servingUnit: 'g',
    perServing: { calories: 592, protein_g: 36, carbs_g: 52, fat_g: 26 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['caesar-salad', 'garden-salad', 'sourdough-bread', 'parmesan'],
    confidenceBase: 0.95,
  },
  {
    id: 'chicken-caesar-wrap',
    name: 'Chicken Caesar Wrap',
    category: 'mixed',
    emoji: '🌯',
    servingSize: 280,
    servingUnit: 'g',
    perServing: { calories: 480, protein_g: 36, carbs_g: 34, fat_g: 20 },
    mealTypes: ['lunch'],
    commonPairings: ['garden-salad', 'french-fries', 'caesar-salad', 'apple'],
    confidenceBase: 0.91,
  },
  {
    id: 'blt-sandwich',
    name: 'BLT Sandwich',
    category: 'mixed',
    emoji: '🥪',
    servingSize: 230,
    servingUnit: 'g',
    perServing: { calories: 440, protein_g: 18, carbs_g: 38, fat_g: 26 },
    mealTypes: ['lunch'],
    commonPairings: ['garden-salad', 'french-fries', 'coleslaw', 'pickled-vegetables'],
    confidenceBase: 0.92,
  },
  {
    id: 'dumplings',
    name: 'Pan-fried Dumplings',
    category: 'mixed',
    emoji: '🥟',
    servingSize: 200,
    servingUnit: 'g',
    perServing: { calories: 360, protein_g: 16, carbs_g: 42, fat_g: 14 },
    mealTypes: ['lunch', 'dinner', 'snack'],
    commonPairings: ['white-rice', 'kimchi', 'fried-rice'],
    confidenceBase: 0.91,
  },
  {
    id: 'bibimbap',
    name: 'Bibimbap',
    category: 'mixed',
    emoji: '🍚',
    servingSize: 400,
    servingUnit: 'g',
    perServing: { calories: 560, protein_g: 28, carbs_g: 80, fat_g: 16 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['kimchi', 'scrambled-eggs', 'sauteed-spinach', 'steamed-carrots', 'pickled-vegetables'],
    confidenceBase: 0.88,
  },
  {
    id: 'beef-stir-fry',
    name: 'Beef Stir Fry',
    category: 'mixed',
    emoji: '🥘',
    servingSize: 350,
    servingUnit: 'g',
    perServing: { calories: 480, protein_g: 36, carbs_g: 40, fat_g: 18 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['white-rice', 'brown-rice', 'bell-peppers', 'steamed-broccoli', 'lo-mein', 'sauteed-mushrooms'],
    confidenceBase: 0.92,
  },
  {
    id: 'chicken-curry-rice',
    name: 'Chicken Curry with Rice',
    category: 'mixed',
    emoji: '🍛',
    servingSize: 400,
    servingUnit: 'g',
    perServing: { calories: 580, protein_g: 34, carbs_g: 62, fat_g: 22 },
    mealTypes: ['lunch', 'dinner'],
    commonPairings: ['white-rice', 'sauteed-spinach', 'pickled-vegetables'],
    confidenceBase: 0.90,
  },
];

export function getFoodsByCategory(category: MockFoodItem['category']): MockFoodItem[] {
  return foodDatabase.filter((item) => item.category === category);
}

export function getFoodsByMealType(type: string): MockFoodItem[] {
  return foodDatabase.filter((item) => item.mealTypes.includes(type));
}

export function getFoodById(id: string): MockFoodItem | undefined {
  return foodDatabase.find((item) => item.id === id);
}
